### ISSUE TITLE
Has this gem been published?

### ISSUE THREAD

**Issue by tfhartmann** [zl4bv/packer-ruby#1]
Hi there!  Is this gem published? I wasn't able to find it...
https://rubygems.org/search?utf8=%E2%9C%93&query=packer

```
gem install packer-client
ERROR:  Could not find a valid gem 'packer-client' (>= 0) in any repository
```

**Comment by zl4bv** [comment]
Hey @tfhartmann, the gem has now been [published](https://rubygems.org/gems/packer-client). Enjoy!

**Comment by tfhartmann** [comment]
Awesome dude! Thanks!
