### ISSUE TITLE
Might be PEBKAC but...

### ISSUE THREAD

**Issue by tfhartmann** [zl4bv/packer-ruby#2]
I'm trying to get the packer lib working, but started running into this error `Bad source ..commonfilesgemrc: stat ..commonfilesgemrc: no such file or directory stderr:` 

The below is the result of my testing using IRB, pretty much following along the README, but I think I may have gone afoul somewhere. 😭  

Anyway, if I run client.validate and only check for syntax, everything looks good!

``` Ruby
?> client.validate(template, {:syntax_only => true })
=> #<Packer::Output::Validate:0x007fca1870e178 @output=<Mixlib::ShellOut#70252985087660: command: 'packer validate -syntax-only /Users/tfhartmann/main.json' process_status: #<Process::Status: pid 43272 exit 0> stdout: Syntax-only check passed Everything looks okay stderr:  child_pid: 43272 environment: {} timeout: 7200 user:  group:  working_dir:
```

However, if I try to do a full validation, passing in my  three required variables :  app_name, aws_region,   and aws_source_linux_ami I get an error.  The build method likewise throws the below error. 

I'm pretty far out of my depth with this, but I did some digging and found this : https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout.rb#L54  which kind of made me wonder of the packer client command method needed to set a working directory?  It doesn't look like it did...  https://github.com/zl4bv/packer-client/blob/master/lib/packer/client.rb#L48 Anyway, this probably could totally be all on me doing something wrong, and any insight would be awesome! oh, and FWIW, my version of mixlib-shellout is 2.2.7

Thanks again for any help! 

``` Ruby
>> client.validate( template ,{ :vars => { :aws_source_linux_ami=>'ami-c481fad3', :app_name=>'bastion', :aws_region =>'us-east-1'}})
=> #<Packer::Output::Validate:0x007fca18657ec8 @output=<Mixlib::ShellOut#70252984690460: command: 'packer validate -var 'aws_source_linux_ami=ami-c481fad3' -var 'app_name=bastion' -var 'aws_region=us-east-1' /Users/tfhartmann/main.json' process_status: #<Process::Status: pid 43222 exit 1> stdout: Template validation failed Errors are shown below

Errors validating build amazon-ebs 1 errors occurred:

 Bad source ..commonfilesgemrc: stat ..commonfilesgemrc: no such file or directory stderr:  child_pid: 43222 environment: {} timeout: 7200 user:  group:  working_dir:
```

**Comment by zl4bv** [comment]
Hey @tfhartmann 

It appears that your Packer template references a file located at `../common/files/gemrc` but Packer is not finding a file at that location.

The packer-client gem doesn't currently let you set a different working directory but this functionality could be added. Alternatively, you could do something like this:

``` ruby
Dir.chdir('/path/to/some/other/dir') do
  client.validate( template ,{ :vars => { :aws_source_linux_ami=>'ami-c481fad3', :app_name=>'bastion', :aws_region =>'us-east-1'}})
end
```

**Comment by zl4bv** [comment]
Another thought is that the file is indeed located at `../common/files/gemrc` but the slashes are being escaped and Packer is instead looking for a file in the current directory called `..commonfilesgemrc`. 

If you run `packer validate -var 'aws_source_linux_ami=ami-c481fad3' -var 'app_name=bastion' -var 'aws_region=us-east-1' /Users/tfhartmann/main.json` from your shell (i.e. without using the gem) does Packer validate the template successfully?

**Comment by tfhartmann** [comment]
> It appears that your Packer template references a file located at ../common/files/gemrc but Packer is not finding a file at that location.

DOH! You are totally right it does! And in my testing,  I was running `packer validate -var 'aws_source_linux_ami=ami-c481fad3' -var 'app_name=bastion' -var 'aws_region=us-east-1' /Users/tfhartmann/main.json` which was validating the template but I was switching tab in my terminal, and running the validate from the packer repo working copy, _not_ the directory I'm writing my ruby code.   I suspect the `Dir.chdir` you suggest will totally work for me... thank you so much for helping me troubleshoot my own stupid! 

I'll give the `Dir.chdir` an try and let you know if it works!

**Comment by tfhartmann** [comment]
Yup! Wrapping my validation / builds in the correct working dir totally work.  Thanks again for the help! And thanks for writing this lib for Packer!

**Comment by zl4bv** [comment]
Excellent, glad you got it working 🙂
