### ISSUE TITLE
How can we view the packer output when instantiated via the client?

### ISSUE THREAD

**Issue by Dombo** [zl4bv/packer-ruby#3]
I can't seem to output logs to STDOUT - any guidance or suggestions on how I could implement it would be appreciated, happy to PR.

**Comment by zl4bv** [comment]
If I understand this correctly you're trying to get the original messages that Packer sends to STDOUT and print them.

You could do something like the following:

```ruby
require 'packer'
client = Packer::Client.new
result = client.build('template.json')

puts result.stdout
```

**Comment by Dombo** [comment]
Appreciate the speedy response - thanks
